// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: healthchecker/v1/healthchecker_v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_OK          State = 1
	State_STATE_WARNING     State = 2
	State_STATE_ERROR       State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_OK",
		2: "STATE_WARNING",
		3: "STATE_ERROR",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_OK":          1,
		"STATE_WARNING":     2,
		"STATE_ERROR":       3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_healthchecker_v1_healthchecker_v1_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_healthchecker_v1_healthchecker_v1_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_healthchecker_v1_healthchecker_v1_proto_rawDescGZIP(), []int{0}
}

type CheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deveui  string `protobuf:"bytes,1,opt,name=deveui,proto3" json:"deveui,omitempty"`
	MeterId string `protobuf:"bytes,2,opt,name=meter_id,json=meterId,proto3" json:"meter_id,omitempty"`
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_healthchecker_v1_healthchecker_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_healthchecker_v1_healthchecker_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_healthchecker_v1_healthchecker_v1_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetDeveui() string {
	if x != nil {
		return x.Deveui
	}
	return ""
}

func (x *CheckRequest) GetMeterId() string {
	if x != nil {
		return x.MeterId
	}
	return ""
}

type CheckChirpstack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastSeen *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Enabled  bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *CheckChirpstack) Reset() {
	*x = CheckChirpstack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_healthchecker_v1_healthchecker_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckChirpstack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChirpstack) ProtoMessage() {}

func (x *CheckChirpstack) ProtoReflect() protoreflect.Message {
	mi := &file_healthchecker_v1_healthchecker_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChirpstack.ProtoReflect.Descriptor instead.
func (*CheckChirpstack) Descriptor() ([]byte, []int) {
	return file_healthchecker_v1_healthchecker_v1_proto_rawDescGZIP(), []int{1}
}

func (x *CheckChirpstack) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *CheckChirpstack) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CheckDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastValid    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_valid,json=lastValid,proto3" json:"last_valid,omitempty"`
	LastNonvalid *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_nonvalid,json=lastNonvalid,proto3" json:"last_nonvalid,omitempty"`
}

func (x *CheckDB) Reset() {
	*x = CheckDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_healthchecker_v1_healthchecker_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDB) ProtoMessage() {}

func (x *CheckDB) ProtoReflect() protoreflect.Message {
	mi := &file_healthchecker_v1_healthchecker_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDB.ProtoReflect.Descriptor instead.
func (*CheckDB) Descriptor() ([]byte, []int) {
	return file_healthchecker_v1_healthchecker_v1_proto_rawDescGZIP(), []int{2}
}

func (x *CheckDB) GetLastValid() *timestamppb.Timestamp {
	if x != nil {
		return x.LastValid
	}
	return nil
}

func (x *CheckDB) GetLastNonvalid() *timestamppb.Timestamp {
	if x != nil {
		return x.LastNonvalid
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chirpstack *CheckChirpstack `protobuf:"bytes,1,opt,name=chirpstack,proto3" json:"chirpstack,omitempty"`
	Db         *CheckDB         `protobuf:"bytes,2,opt,name=db,proto3" json:"db,omitempty"`
	State      State            `protobuf:"varint,3,opt,name=state,proto3,enum=healthchecker.v1.State" json:"state,omitempty"`
	Deveui     string           `protobuf:"bytes,4,opt,name=deveui,proto3" json:"deveui,omitempty"`
	MeterId    string           `protobuf:"bytes,5,opt,name=meter_id,json=meterId,proto3" json:"meter_id,omitempty"`
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_healthchecker_v1_healthchecker_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_healthchecker_v1_healthchecker_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_healthchecker_v1_healthchecker_v1_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetChirpstack() *CheckChirpstack {
	if x != nil {
		return x.Chirpstack
	}
	return nil
}

func (x *CheckResponse) GetDb() *CheckDB {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *CheckResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *CheckResponse) GetDeveui() string {
	if x != nil {
		return x.Deveui
	}
	return ""
}

func (x *CheckResponse) GetMeterId() string {
	if x != nil {
		return x.MeterId
	}
	return ""
}

var File_healthchecker_v1_healthchecker_v1_proto protoreflect.FileDescriptor

var file_healthchecker_v1_healthchecker_v1_proto_rawDesc = []byte{
	0x0a, 0x27, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x2f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72,
	0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x0c,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x76, 0x65, 0x75, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65,
	0x76, 0x65, 0x75, 0x69, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x64, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x68, 0x69, 0x72, 0x70, 0x73, 0x74, 0x61,
	0x63, 0x6b, 0x12, 0x37, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x07, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44,
	0x42, 0x12, 0x39, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x3f, 0x0a, 0x0d,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x6f, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0c, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x6f, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0xdf, 0x01,
	0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x0a, 0x63, 0x68, 0x69, 0x72, 0x70, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x68, 0x69, 0x72,
	0x70, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x52, 0x0a, 0x63, 0x68, 0x69, 0x72, 0x70, 0x73, 0x74, 0x61,
	0x63, 0x6b, 0x12, 0x29, 0x0a, 0x02, 0x64, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x42, 0x52, 0x02, 0x64, 0x62, 0x12, 0x2d, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x76, 0x65, 0x75, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65,
	0x76, 0x65, 0x75, 0x69, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x49, 0x64, 0x2a,
	0x50, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02,
	0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x03, 0x32, 0x58, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x48, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x1e, 0x2e, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67,
	0x6f, 0x2e, 0x78, 0x73, 0x66, 0x78, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x74, 0x77, 0x69, 0x72, 0x70,
	0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f,
	0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_healthchecker_v1_healthchecker_v1_proto_rawDescOnce sync.Once
	file_healthchecker_v1_healthchecker_v1_proto_rawDescData = file_healthchecker_v1_healthchecker_v1_proto_rawDesc
)

func file_healthchecker_v1_healthchecker_v1_proto_rawDescGZIP() []byte {
	file_healthchecker_v1_healthchecker_v1_proto_rawDescOnce.Do(func() {
		file_healthchecker_v1_healthchecker_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_healthchecker_v1_healthchecker_v1_proto_rawDescData)
	})
	return file_healthchecker_v1_healthchecker_v1_proto_rawDescData
}

var file_healthchecker_v1_healthchecker_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_healthchecker_v1_healthchecker_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_healthchecker_v1_healthchecker_v1_proto_goTypes = []interface{}{
	(State)(0),                    // 0: healthchecker.v1.State
	(*CheckRequest)(nil),          // 1: healthchecker.v1.CheckRequest
	(*CheckChirpstack)(nil),       // 2: healthchecker.v1.CheckChirpstack
	(*CheckDB)(nil),               // 3: healthchecker.v1.CheckDB
	(*CheckResponse)(nil),         // 4: healthchecker.v1.CheckResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_healthchecker_v1_healthchecker_v1_proto_depIdxs = []int32{
	5, // 0: healthchecker.v1.CheckChirpstack.last_seen:type_name -> google.protobuf.Timestamp
	5, // 1: healthchecker.v1.CheckDB.last_valid:type_name -> google.protobuf.Timestamp
	5, // 2: healthchecker.v1.CheckDB.last_nonvalid:type_name -> google.protobuf.Timestamp
	2, // 3: healthchecker.v1.CheckResponse.chirpstack:type_name -> healthchecker.v1.CheckChirpstack
	3, // 4: healthchecker.v1.CheckResponse.db:type_name -> healthchecker.v1.CheckDB
	0, // 5: healthchecker.v1.CheckResponse.state:type_name -> healthchecker.v1.State
	1, // 6: healthchecker.v1.CheckService.Check:input_type -> healthchecker.v1.CheckRequest
	4, // 7: healthchecker.v1.CheckService.Check:output_type -> healthchecker.v1.CheckResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_healthchecker_v1_healthchecker_v1_proto_init() }
func file_healthchecker_v1_healthchecker_v1_proto_init() {
	if File_healthchecker_v1_healthchecker_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_healthchecker_v1_healthchecker_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_healthchecker_v1_healthchecker_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckChirpstack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_healthchecker_v1_healthchecker_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_healthchecker_v1_healthchecker_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_healthchecker_v1_healthchecker_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_healthchecker_v1_healthchecker_v1_proto_goTypes,
		DependencyIndexes: file_healthchecker_v1_healthchecker_v1_proto_depIdxs,
		EnumInfos:         file_healthchecker_v1_healthchecker_v1_proto_enumTypes,
		MessageInfos:      file_healthchecker_v1_healthchecker_v1_proto_msgTypes,
	}.Build()
	File_healthchecker_v1_healthchecker_v1_proto = out.File
	file_healthchecker_v1_healthchecker_v1_proto_rawDesc = nil
	file_healthchecker_v1_healthchecker_v1_proto_goTypes = nil
	file_healthchecker_v1_healthchecker_v1_proto_depIdxs = nil
}
